sudo: required
services:
  - docker
addons:
  apt:
    packages:
    - xsltproc
language: erlang
otp_release:
- 17.5
script: make test
deploy:
  provider: releases
  api_key:
    secure: ktklMK+XMOteFt+m9NHhVqKkA1Wo8f9L/cJphUmBMgb3TS+4+vAU50yY8omIyprS8poc3mBWxjYD9p9xdeDnXY2tiFrLDKCWU/jbH3awD0uL6W0Di8BYAVOGhr2Jjjp6gi/B67wHtCtzEoSSNNfMMZ+RWf4GZjJ96NXOLhPRx4k=
  file: "plugins/autocluster-${TRAVIS_TAG}.ez"
  on:
    tags: true
    repo: aweber/rabbitmq-autocluster

