#cloud-config
coreos:
  units:
    - name: consul.service
      command: start
      content: |
        [Unit]
        Description=consul

        [Service]
        ExecStart=/opt/consul/bin/bootstrap.sh

  update:
    reboot-strategy: off

write_files:
  - path: /home/core/bin/containers
    permissions: 0755
    owner: core
    content: |
      #!/bin/bash

      IFS=$'\n';
      echo
      echo "Container Name                 IP Address"
      echo "-----------------------------------------------"
      for CONTAINER in `docker ps | awk '{print $(NF)}' | tail -n+2`
      do
        IFS=,
        C=($CONTAINER)
        IP=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${C}`
        echo "$C $IP" | awk '{printf "%-30s %-20s\n", $1, $2}'
      done
      echo
  - path: /home/core/.ssh/id_rsa
    permissions: 0400
    owner: core
    content: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAx6WFY4TQHD+Osw1wmhUJGoW0sXx17t+F0q12nr68zsCIlPi7
      5udOZQ0DbYxzZ4gCubsgR0dtJ9Swy4RSDWzUHk69CS+CxdXEH+MYoJNbuAqMMveD
      n3EDlNbQSlByNt6rE0VfcM8xa3YgVGfwegArCGSzUC8ep3DEwGb/0I1IdWLiVAJk
      yZu/ZWt7AIyZIb5wrO4OcOhlzC2HFwyOSM/1nDfRiPmMiuUzVpJxLpPkH0W6fbv0
      PeRD1vPSnplbrmr8Tdif3SSc4RA0KRUkxYEYsVC4SuDvchxCv3p8fBgCGqTKkg15
      opZwGbKpcq2JxsLjaHNvwVwVIQonPiWfIvXAMwIDAQABAoIBAQCNrZzXXu0A3um5
      jxQVhFANjk0IlzZp6h3hwE+pn9oFLwS+EzXlSsiLVYzVNRLAqfilLXJeowWHepxs
      EN7ZwB1X1LC50AmRs32W02Yqregs1u9fS98QSvcrrLXrxuMGpUXqSxTLzX1YsV+I
      BqrVKUFgl3XYtVefo5s8nttzeI+vHNfs0wAbEvaXJuFKZlvkfVgzFsyjE8FWhHJ4
      r2+E4/3aObLyN21bT1w+8sW+xLAsExdQpe6vnHBJs5Jl8qxuBxpYLOKNgj6nhxR1
      Gypno/64HR2sxxikJB17arPdFe3aH/BqMo3MdSo+ekCXHFPKb5HYm9jmWThnnGol
      vKBvozNhAoGBAO+4510alzHMzd8gFNHdhr+WG3uGtMdj3qciY6n+SJ8RAJuYD40Z
      GmNGycFnho+KL358Q+bAlKrIEzmKALeOQ/Qn3ajPUDk+uCOb7Dak1qXX+1H0AlKn
      nsAF5baLtcKm3Gov1KDmMBhc8S59H226iwPebsw5fJ9wr4UyNMuX3ncPAoGBANUz
      +wLZsXiaBEZrRP4vXCY4lMsuit9py6TPVEbL7fKSOELYCwE2fpyjOFAJOVPfpJUR
      n4MZgmpTIg5cR7Det+gHSrhg4EciK1jEvBPI0u0c3OMPLPc40SAAA8pdoDYpFrk8
      ROmQGxfjTlrT7dOdwkZnqUHIMm3pfEnU8nzbrYSdAoGBAJOOaTtx5qcMvZweDzKu
      /QZoyznZzOT+oEqYbGhy0Ri4Snt7ufbMAOYi6IVXyAgKsvlUXCdpWxlUViEQxSg3
      NbTP5SzHj0XtSUMB8wAfrtAeheAIJnXiH2FrP96BWLwcIYhrMKJpjikw7HQFKJdO
      P8t92w1yRTePETsXkE/Rh2oZAoGAcs+XMKXCaEuoWbOSZ79hREPb/L6HkmAKhioQ
      HD/dV29eVMC6zGBoNjm/LXqKIJyiqJPg7lxiWpeCE3GmOZz2NEEY/8lLfYLtDNSE
      47KVw5JzcOLPOCKkmzLm16cri378+at3AL/VlzuVClxuCjM+V2OjRgVlAsNlZu0B
      2DMEchECgYAs4rHtibhtMwJ5gTeyFIoU448MM3u/G2eQEbso0WyaY46mmdMD3Acz
      Qf1jBeTjjTwjAgQd1jniNu79qLyCaaMedIlLF0dQRQ+od4BNZqCs12cUV+mtsOLw
      vEfg8QcSTXlVLHZ8lNgVrSbvSpmsb5BDkuEM6SimvKK/Wfx8U2AJwg==
      -----END RSA PRIVATE KEY-----
  - path: /home/core/.ssh/id_rsa.pub
    permissions: 0644
    owner: core
    content: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHpYVjhNAcP46zDXCaFQkahbSxfHXu34XSrXaevrzOwIiU+Lvm505lDQNtjHNniAK5uyBHR20n1LDLhFINbNQeTr0JL4LF1cQf4xigk1u4Cowy94OfcQOU1tBKUHI23qsTRV9wzzFrdiBUZ/B6ACsIZLNQLx6ncMTAZv/QjUh1YuJUAmTJm79la3sAjJkhvnCs7g5w6GXMLYcXDI5Iz/WcN9GI+YyK5TNWknEuk+QfRbp9u/Q95EPW89KemVuuavxN2J/dJJzhEDQpFSTFgRixULhK4O9yHEK/enx8GAIapMqSDXmilnAZsqlyrYnGwuNoc2/BXBUhCic+JZ8i9cAz gavinr@gmr-aw-mbp.local
  - path: /home/core/.ssh/config
    permissions: 0644
    owner: core
    content: |
      Host *
        User root
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null
  - path: /etc/consul.d/server.json
    permissions: 0644
    content: |
      {
        "bootstrap": true,
        "bind_addr": "$public_ipv4",
        "client_addr": "$public_ipv4",
        "data_dir": "/var/lib/consul",
        "datacenter": "rmq",
        "server": true,
        "ui_dir": "/opt/consul/webui/dist"
      }
  - path: /opt/consul/bin/bootstrap.sh
    permissions: 0755
    content: |
      #!/bin/bash

      if [ ! -f /opt/consul/bin/consul ]; then
        curl -o /tmp/consul.zip -L https://dl.bintray.com/mitchellh/consul/0.4.0_linux_amd64.zip
        unzip /tmp/consul.zip -d /opt/consul/bin/
        chmod +x /opt/consul/consul
        curl -L -o /tmp/webui.zip https://dl.bintray.com/mitchellh/consul/0.4.0_web_ui.zip
        mkdir /opt/consul/webui
        unzip /tmp/webui.zip -d /opt/consul/webui/
        rm /tmp/consul.zip /tmp/webui.zip
      fi

      GOMAXPROCS=10 /opt/consul/bin/consul agent --config-dir=/etc/consul.d
