#cloud-config
coreos:
  etcd2:
    advertise-client-urls: http://$public_ipv4:2379
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001

  units:
    - name: etcd2.service
      command: start

    - name: consul.service
      command: start
      content: |
        [Unit]
        Description=consul

        [Service]
        ExecStart=/opt/consul/bin/bootstrap.sh

  update:
    reboot-strategy: off

write_files:
  - path: /etc/consul.d/server.json
    permissions: 0644
    content: |
      {
        "bootstrap": true,
        "bind_addr": "$public_ipv4",
        "client_addr": "$public_ipv4",
        "data_dir": "/var/lib/consul",
        "datacenter": "rmq",
        "server": true,
        "ui_dir": "/opt/consul/webui/dist"
      }
  - path: /opt/consul/bin/bootstrap.sh
    permissions: 0755
    content: |
      #!/bin/bash

      if [ ! -f /opt/consul/bin/consul ]; then
        curl -o /tmp/consul.zip -L https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip
        unzip /tmp/consul.zip -d /opt/consul/bin/
        chmod +x /opt/consul/consul
        curl -L -o /tmp/webui.zip https://dl.bintray.com/mitchellh/consul/0.5.2_web_ui.zip
        mkdir /opt/consul/webui
        unzip /tmp/webui.zip -d /opt/consul/webui/
        rm /tmp/consul.zip /tmp/webui.zip
      fi

      GOMAXPROCS=10 /opt/consul/bin/consul agent --config-dir=/etc/consul.d
